# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
from table import Ui_Form


class Ui_MainWindow(object):
    def koneksi(self):
        con = pymysql.connect(db='formulir', user='root', passwd='',
                              host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        if(cur):
            self.messagebox("Koneksi", "Koneksi Berhasil")
        else:
            self.messagebox("Koneksi", "Koneksi Gagal")

    def messagebox(self, title, message):
        mess = QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

    def simpanData(self):
        namaLengkap = self.plainTextEdit.toPlainText()
        tempatLahir = self.plainTextEdit_2.toPlainText()
        tanggalLahir = self.plainTextEdit_3.toPlainText()
        nik = self.plainTextEdit_4.toPlainText()
        nohp = self.plainTextEdit_5.toPlainText()
        email = self.plainTextEdit_6.toPlainText()
        jenisKelamin = self.plainTextEdit_7.toPlainText()
        insert = (namaLengkap, tempatLahir, tanggalLahir,
                  nik, nohp, email, jenisKelamin)
        print(insert)
        con = pymysql.connect(db='formulir', user='root', passwd='',
                              host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        sql = "INSERT INTO datadiri (namaLengkap, tempatLahir, tanggalLahir, nik, nohp,email, jenisKelamin) VALUES " + str(
            insert)
        data = cur.execute(sql)
        if(data):
            self.messagebox("BERHASIL", "Data Anda tersimpan")
        else:
            self.messagebox("GAGAL", "Data Anda tidak tersimpan")

    def ubahData(self):
        namaLengkap = self.plainTextEdit.toPlainText()
        tempatLahir = self.plainTextEdit_2.toPlainText()
        tanggalLahir = self.plainTextEdit_3.toPlainText()
        nik = self.plainTextEdit_4.toPlainText()
        nohp = self.plainTextEdit_5.toPlainText()
        email = self.plainTextEdit_6.toPlainText()
        jenisKelamin = self.plainTextEdit_7.toPlainText()
        # insert = (namaLengkap, tempatLahir, tanggalLahir, nik, nohp, email)
        # print(insert)
        con = pymysql.connect(db='formulir', user='root', passwd='',
                              host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        sql = "UPDATE datadiri SET namaLengkap=%s, tempatLahir=%s, tanggalLahir=%s, nik=%s, nohp=%s, email=%s, jenisKelamin=%s"
        data = cur.execute(sql, (namaLengkap, tempatLahir, tanggalLahir,
                                 nik, nohp, email, jenisKelamin))
        if(data):
            self.messagebox("BERHASIL", "Data Anda tersimpan")
        else:
            self.messagebox("GAGAL", sql)

    def hapusData(self):
        nama = self.plainTextEdit.toPlainText()
        con = pymysql.connect(db='formulir', user='root', passwd='',
                              host='localhost', port=3306, autocommit=True)
        cur = con.cursor()
        sql = "DELETE FROM datadiri WHERE namaLengkap=%s"
        data = cur.execute(sql, (nama))
        if(data):
            self.messagebox("BERHASIL", "Data ANDA sudah terhapus")
        else:
            self.messagebox("GAGAL", "Data Anda belum  terhapus")

    def lihatData(self):
        self.window = QtWidgets.QApplication(sys.argv)
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form()
        self.ui.setupUi(self.Form)
        self.Form.show()

    # Bagian ini jangan di ubah-ubah gan

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(818, 545)
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 811, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 50, 821, 31))
        self.label_2.setStyleSheet("background-color: gray;\n"
                                   "color: white;\n"
                                   "opacity: 0.6;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 111, 17))
        self.label_3.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 130, 381, 31))
        self.plainTextEdit.setStyleSheet("color: gray;\n"
                                         "font-size: 12px;")
        self.plainTextEdit.setInputMethodHints(
            QtCore.Qt.ImhEmailCharactersOnly | QtCore.Qt.ImhMultiLine)
        self.plainTextEdit.setReadOnly(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 111, 17))
        self.label_4.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(10, 200, 181, 31))
        self.plainTextEdit_2.setStyleSheet("color: gray;\n"
                                           "font-size: 12px;")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(210, 170, 111, 17))
        self.label_5.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(210, 200, 181, 31))
        self.plainTextEdit_3.setStyleSheet("color: gray;\n"
                                           "font-size: 12px;")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(410, 100, 171, 17))
        self.label_6.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(410, 130, 391, 31))
        self.plainTextEdit_4.setStyleSheet("color: gray;\n"
                                           "font-size: 12px;")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(410, 170, 111, 17))
        self.label_7.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(410, 250, 141, 17))
        self.label_8.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(410, 290, 391, 31))
        self.plainTextEdit_5.setStyleSheet("color: gray;\n"
                                           "font-size: 12px;")
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 250, 111, 17))
        self.label_9.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_6.setGeometry(QtCore.QRect(10, 290, 381, 31))
        self.plainTextEdit_6.setStyleSheet("color: gray;\n"
                                           "font-size: 12px;")
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 440, 251, 41))
        self.pushButton.setStyleSheet("background-color: green;\n"
                                      "color: white;\n"
                                      "border-radius: 5px;\n"
                                      "")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.simpanData)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(10, 400, 301, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(520, 330, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: orange;\n"
                                        "color: white;\n"
                                        "border-radius: 5px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.ubahData)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(630, 330, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: red;\n"
                                        "color: white;\n"
                                        "border-radius: 5px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.hapusData)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(410, 330, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: blue;\n"
                                        "color: white;\n"
                                        "border-radius: 5px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.lihatData)
        self.plainTextEdit_7 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_7.setGeometry(QtCore.QRect(410, 200, 391, 31))
        self.plainTextEdit_7.setStyleSheet("color: gray;\n"
                                           "font-size: 12px;")
        self.plainTextEdit_7.setPlainText("")
        self.plainTextEdit_7.setObjectName("plainTextEdit_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate(
            "MainWindow", "Formulir Pendaftaran Mahasiswa Baru"))
        self.label_2.setText(_translate("MainWindow", "Data Diri"))
        self.label_3.setText(_translate("MainWindow", "Nama Lengkap :"))
        self.plainTextEdit.setPlainText(_translate(
            "MainWindow", "Masukkan Nama Lengkap"))
        self.label_4.setText(_translate("MainWindow", "Tempat Lahir :"))
        self.plainTextEdit_2.setPlainText(
            _translate("MainWindow", "Masukkan Tempat Lahir"))
        self.label_5.setText(_translate("MainWindow", "Tanggal Lahir :"))
        self.plainTextEdit_3.setPlainText(_translate("MainWindow", "dd/mm/yy"))
        self.label_6.setText(_translate(
            "MainWindow", "Nomor  Identitas (NIK) :"))
        self.plainTextEdit_4.setPlainText(
            _translate("MainWindow", "Masukkan Nomor NIK"))
        self.label_7.setText(_translate("MainWindow", "Jenis Kelamin :"))
        self.label_8.setText(_translate("MainWindow", "Masukkan NO HP :"))
        self.plainTextEdit_5.setPlainText(
            _translate("MainWindow", "Masukkan No Hp"))
        self.label_9.setText(_translate("MainWindow", "Email :"))
        self.plainTextEdit_6.setPlainText(
            _translate("MainWindow", "Masukkan Email"))
        self.pushButton.setText(_translate("MainWindow", "Simpan Data"))
        self.checkBox.setText(_translate(
            "MainWindow", "Saya menyatakan bahwa data yang saya sudah isi  BENAR"))
        self.pushButton_2.setText(_translate("MainWindow", "Ubah Data"))
        self.pushButton_3.setText(_translate("MainWindow", "Hapus Data"))
        self.pushButton_4.setText(_translate("MainWindow", "Lihat Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
